services:
  backend:
    build:
      context: ./faceID
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./faceID:/app
    working_dir: /app
    env_file:
      - ./faceID/.env
    environment:
      - DEBUG=False
    restart: unless-stopped
    
  frontend:
    build:
      context: ./faceID-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./faceID-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

  # Loại bỏ container mongo local nếu chỉ sử dụng MongoDB Atlas
  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

volumes:
  mongodb_data: