"""
Django settings for faceID project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Tải biến môi trường từ file .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# MongoDB Connection Settings
MONGO_URI = os.environ.get('MONGO_URI')
MONGO_DB_NAME = os.environ.get('MONGO_DB_NAME', 'pmmnm')
MONGO_COLLECTIONS = {
    'dataset': 'dataset',
    'signin': 'signin',
    'testdata': 'testdata',
    'trainner': 'trainner',
    'attendance': 'attendance',
    'employees': 'employees',
    'work_schedule': 'work_schedule',
}

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-key-for-dev')


DEBUG = os.environ.get('DEBUG', 'False') == 'True'

#ALLOWED_HOSTS = ['*','backend','localhost'] 
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'awaited-easy-marten.ngrok-free.app',  # <-- domain ngrok cố định
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'faceIDatt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",  # Thêm dòng này lên đầu middleware

]

ROOT_URLCONF = 'faceID.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'faceID.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Chỉ cho phép user đã xác thực
    ],
}

# JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTHENTICATION_BACKENDS = [
    'faceIDatt.auth.MongoDBAuthBackend',  # Custom MongoDB backend
    'django.contrib.auth.backends.ModelBackend',  # Giữ lại backend mặc định
]

# CORS settings
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-timezone-offset',
    'cache-control',
    'pragma',
    'if-modified-since',
    'if-none-match', 
]
#CORS_ALLOW_ALL_ORIGINS = True  
# CORS_ALLOWED_ORIGINS = [
#   "http://localhost:5173",
#    "http://127.0.0.1:5173",
#    "http://localhost:8000",
# ]
CORS_ALLOWED_ORIGINS = [
    "https://faceidwebapp-mu.vercel.app",
    "https://awaited-easy-marten.ngrok-free.app",  # <-- thêm domain ngrok
    "https://frontendfaceidwebapp.vercel.app",       # <- thêm dòng này

 ]

CORS_ALLOW_CREDENTIALS = True


# Định nghĩa đường dẫn đến thư mục chứa mô hình nhận diện khuôn mặt
FACE_MODELS_DIR = os.path.join(BASE_DIR, 'faceIDatt', 'models')
os.makedirs(FACE_MODELS_DIR, exist_ok=True)

# Định nghĩa đường dẫn đến thư mục chứa mô hình nhận diện khuôn mặt
FACE_DATA_DIR = os.path.join(BASE_DIR, 'faceIDatt', 'data')
os.makedirs(FACE_DATA_DIR, exist_ok=True)

# Đường dẫn đến thư mục chứa ảnh đã được nhận diện
DATA_FACES_FROM_CAMERA_DIR = os.path.join(FACE_DATA_DIR, 'faces_from_camera')
os.makedirs(DATA_FACES_FROM_CAMERA_DIR, exist_ok=True)

# Cài đặt logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'faceID.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'faceIDatt': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://172.18.0.3:5173',
    "https://faceidwebapp-mu.vercel.app",
    "https://awaited-easy-marten.ngrok-free.app",  # <-- thêm domain ngrok
    "https://frontendfaceidwebapp.vercel.app",       # <- thêm dòng này

    
]

# Tạo thư mục logs nếu chưa tồn tại
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)
